name: make CI

on:
  push:
    branches: 
      - master
      - dev
  pull_request:
    branches:
      - master
      - dev

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Install requirements
      run: |
        python3 -m pip install --upgrade pip
        python3 -m pip install -r requirements.txt
    - name: make
      run: make
    - name: make test
      run: |
        export PATH=${PATH}:~/.local/bin
        make test
